### PR TITLE
Kevin/authentication

### PR DESCRIPTION
**Pull request by KevinetPeng**
- Implemented basic authentication endpoints
- Added helper for access token checking
- Still need to implement change username/password and account deletion

### CODE REVIEW

**Comment by KevinetPeng** [comment]
Found a security issue with the endpoints. Don't bother reviewing for now, I'll update tn

**Comment by KevinetPeng** [comment]
Security issue should be fixed in latest commit

**Review by tiffwu1027 — APPROVED** [review]
LGTM! Side note: are we  switching all strings to use `''` instead of `""` now?

**Comment by KevinetPeng** [comment]
> 
> 
> LGTM! Side note: are we switching all strings to use `''` instead of `""` now?

It's happening bc of my Prettier extension lmao. Just use whatever you want tbh

**Review by maelliott1010 — APPROVED** [review]
Everything looks good to me as well (sorry I have had this review open for like 4 days and forgot to submit until now...)

**Pull request merged**
